### ISSUE TITLE
Getting Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete

### ISSUE THREAD

**Issue by infominezsanjay** [cardinal-labs/cardinal-staking#133]
We are getting following error while Staking a token.

Failed transaction:  (8) ['Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i invoke [1]', 'Program log: Instruction: InitEntry', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', "Program log: panicked at 'called `Option::unwrap()…l-stake-pool/src/instructions/init_entry.rs:54:64", 'Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i consumed 20622 of 200000 compute units', 'Program failed to complete: BPF program panicked', 'Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i failed: Program failed to complete']0: "Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i invoke [1]"1: "Program log: Instruction: InitEntry"2: "Program 11111111111111111111111111111111 invoke [2]"3: "Program 11111111111111111111111111111111 success"4: "Program log: panicked at 'called `Option::unwrap()` on a `None` value', programs/cardinal-stake-pool/src/instructions/init_entry.rs:54:64"5: "Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i consumed 20622 of 200000 compute units"6: "Program failed to complete: BPF program panicked"7: "Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i failed: Program failed to complete"length: 8[[Prototype]]: Array(0) Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (index.browser.esm.js?156f:7391:1)
    at async Connection.sendRawTransaction (index.browser.esm.js?156f:7352:1)
    at async sendAndConfirmRawTransaction (index.browser.esm.js?156f:9705:1)

**Comment by gchatz22** [comment]
Hey @infominezsanjay curious about what action you followed to get this error. Could you maybe share your pool id + the mint id of the token you tried to `init_entry` for?

**Comment by infominezsanjay** [comment]
Pool ID : J4CFm7XPdm1j5azDVrXiZkaomTZkbvtdkp89MUFbHxDT
 mint id :  FivYbK9CCfPHGrr6fG138ZaDK6yHKcvKTYEXT6EHzsRX

**Comment by gchatz22** [comment]
Hey the issue should be resolved with this PR https://github.com/cardinal-labs/cardinal-staking/pull/140. Basically safely unwrapping any collections/creators. Let me know if everything is okay and will close.

**Comment by infominezsanjay** [comment]
Still Getting same error .
I am running it from this UI  code [](https://github.com/cardinal-labs/cardinal-staking-ui)
Mint ID : FivYbK9CCfPHGrr6fG138ZaDK6yHKcvKTYEXT6EHzsRX
Pool ID : J4CFm7XPdm1j5azDVrXiZkaomTZkbvtdkp89MUFbHxDT


**Error :** 
Failed transaction:  (8) ['Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i invoke [1]', 'Program log: Instruction: InitEntry', 'Program 11111111111111111111111111111111 invoke [2]', 'Program 11111111111111111111111111111111 success', "Program log: panicked at 'called `Option::unwrap()…l-stake-pool/src/instructions/init_entry.rs:54:64", 'Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i consumed 17622 of 200000 compute units', 'Program failed to complete: BPF program panicked', 'Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i failed: Program failed to complete']0: "Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i invoke [1]"1: "Program log: Instruction: InitEntry"2: "Program 11111111111111111111111111111111 invoke [2]"3: "Program 11111111111111111111111111111111 success"4: "Program log: panicked at 'called `Option::unwrap()` on a `None` value', programs/cardinal-stake-pool/src/instructions/init_entry.rs:54:64"5: "Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i consumed 17622 of 200000 compute units"6: "Program failed to complete: BPF program panicked"7: "Program stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i failed: Program failed to complete"length: 8[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}[[Prototype]]: Object Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (index.browser.esm.js?156f:7391:1)
    at async Connection.sendRawTransaction (index.browser.esm.js?156f:7352:1)
    at async sendAndConfirmRawTransaction (index.browser.esm.js?156f:9705:1)

**Comment by gchatz22** [comment]
Checking in, are you still experiencing this issue? We deployed this fix on safely unwrapping an optional value in that instruction https://github.com/cardinal-labs/cardinal-staking/pull/140

**Comment by gchatz22** [comment]
Closing due to inactivity
